version: "3"
services:
#  server:
#    build:
#      context: backend
#      dockerfile: Dockerfile
#    depends_on:
#      - mongo
#    ports:
#      - 3100:3100
#    env_file: backend/.env
#    environment:
#      - MONGO_HOST=mongo
#      - WAIT_HOSTS=mongo:27017
#
#  client:
#    build:
#      context: .
#      dockerfile: frontend/Dockerfile
#    depends_on:
#      - server
#    ports:
#      - 443:443
#      - 80:80

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh
      - ./database/mongo:/data/db
    env_file: backend/.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin

  mongo-express:
    image: mongo-express
    restart: always
    depends_on:
      - mongo
    ports:
      - 8083:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=admin
#      - ME_CONFIG_SITE_BASEURL=/some-hash
#      - ME_CONFIG_MONGODB_ENABLE_ADMIN=false
#      - ME_CONFIG_BASICAUTH_USERNAME=root
#      - ME_CONFIG_BASICAUTH_PASSWORD=root
#      - ME_CONFIG_MONGODB_AUTH_DATABASE=
#      - ME_CONFIG_MONGODB_AUTH_USERNAME=
#      - ME_CONFIG_MONGODB_AUTH_PASSWORD=